assume_yes: false
config: test_config.yaml
debug: false
device:
- 0
eval_interval: 1
eval_start: 1
feeder: feeders.feeder.Feeder
ignore_weights: []
log_interval: 100
loss: CrossEntropy
loss_args: {}
mixed: false
model: models.hf_posergb.HF_PoseRGB
model_args:
  MIB_block: true
  dropout: 0.2
  embedding_dim_final: 256
  include_orientation_in_global_wrist_ref: true
  microaction_window_size: 15
  modality: both
  num_classes: 1380
  num_joints: 21
  num_nouns: 90
  num_verbs: 24
  rgb_frames_to_use: -1
  rgb_input_feat_dim: 1536
  separate_hands: true
  tf_heads: 8
  tf_layers: 2
  trajectory_atten_dim_per_head: 4
  trajectory_tcn_dilations:
  - 1
  - 2
  trajectory_tcn_kernel_size: 3
  trajectory_tcn_stride:
  - 1
  - 2
  - 2
  use_2d_pose: false
  use_both_wrists: true
  use_global_wrist_reference: true
num_worker: 8
phase: test
print_log: true
save_interval: 1
save_score: true
seed: 54
show_topk:
- 1
test_batch_size: 32
test_feeder_args:
  DINO_feature_path: /mnt/ssd/Datasets/assembly101/dinov2_feats_assembly/
  TSM_feature_path: /mnt/ssd/Datasets/assembly101/TSM_features/
  annotations_path: /mnt/ssd/Datasets/assembly101/data/assembly101-annotations
  crop_scale: both
  data_path: /mnt/ssd/Datasets/assembly101/Assembly101_AR_fusion_data/data/HAND_GCN/RAW_contex30_thresh0/
  debug: false
  label_path: /mnt/ssd/Datasets/assembly101/Assembly101_AR_fusion_data/data/Label_contex30_thresh0/
  p_interval:
  - 0.85
  pose_fps: 60
  rgb_data_path: /mnt/ssd/Datasets/assembly101/Assembly101_AR_fusion_data/data/HAND_VID/RAW_contex30_thresh0/
  rgb_feature_source: dino
  rgb_sampling_within_window: first
  sample_cnt_pose: 120
  sample_cnt_vid: 8
  sampling_strategy: crop_and_resize
  split_name: validation
  target_type: action
weights: /home/umurotti/remote_workspace/experiments/HandFormer/work_dirs/handformer_B21x8/weights/weights-2-2778.pt
work_dir: /home/umurotti/remote_workspace/experiments/HandFormer/work_dirs/handformer_B21x8_test/
