action_loss_weight: 1.0
add_feat_loss: true
add_noun_loss: true
add_verb_loss: true
amp_opt_level: 1
assume_yes: false
base_lr: 0.025
batch_size: 32
checkpoint: null
config: train_config.yaml
debug: false
device:
- 0
- 1
eval_interval: 1
eval_start: 1
feat_loss_weight: 2.0
feeder: feeders.feeder.Feeder
forward_batch_size: 32
ignore_weights: []
log_interval: 100
loss: LabelSmoothingCrossEntropy
loss_args:
  smoothing: 0.1
  temperature: 1.1
lr_decay_rate: 0.1
mixed: false
model: models.hf_posergb.HF_PoseRGB
model_args:
  MIB_block: true
  dropout: 0.2
  embedding_dim_final: 256
  include_orientation_in_global_wrist_ref: true
  microaction_window_size: 15
  modality: both
  num_classes: 1380
  num_joints: 21
  num_nouns: 90
  num_verbs: 24
  rgb_frames_to_use: -1
  rgb_input_feat_dim: 1536
  separate_hands: true
  tf_heads: 8
  tf_layers: 2
  trajectory_atten_dim_per_head: 4
  trajectory_tcn_dilations:
  - 1
  - 2
  trajectory_tcn_kernel_size: 3
  trajectory_tcn_stride:
  - 1
  - 2
  - 2
  use_2d_pose: false
  use_both_wrists: true
  use_global_wrist_reference: true
nesterov: true
noun_loss_weight: 1.0
num_epoch: 50
num_worker: 12
optimizer: SGD
optimizer_states: null
phase: train
print_log: true
save_interval: 1
save_score: true
seed: 150
show_topk:
- 1
start_epoch: 0
step:
- 25
- 40
test_batch_size: 32
test_feeder_args:
  crop_scale: both
  data_path: /mnt/ssd/assembly101/Assembly101_AR_fusion_data/data/HAND_GCN/RAW_contex30_thresh0/
  debug: false
  label_path: /mnt/ssd/assembly101/Assembly101_AR_fusion_data/data/Label_contex30_thresh0/
  p_interval:
  - 0.85
  pose_fps: 60
  rgb_data_path: /mnt/ssd/assembly101/Assembly101_AR_fusion_data/data/HAND_VID/RAW_contex30_thresh0/
  rgb_feature_source: dino
  rgb_sampling_within_window: first
  sample_cnt_pose: 120
  sample_cnt_vid: 8
  sampling_strategy: crop_and_resize
  split_name: validation
  target_type: action
train_feeder_args:
  crop_scale: both
  data_path: /mnt/ssd/assembly101/Assembly101_AR_fusion_data/data/HAND_GCN/RAW_contex30_thresh0/
  debug: false
  label_path: /mnt/ssd/assembly101/Assembly101_AR_fusion_data/data/Label_contex30_thresh0/
  p_interval:
  - 0.7
  - 1.0
  pose_fps: 60
  rgb_data_path: /mnt/ssd/assembly101/Assembly101_AR_fusion_data/data/HAND_VID/RAW_contex30_thresh0/
  rgb_feature_source: dino
  rgb_sampling_within_window: first
  sample_cnt_pose: 120
  sample_cnt_vid: 8
  sampling_strategy: crop_and_resize
  split_name: train
  target_type: action
verb_loss_weight: 1.0
warm_up_epoch: 5
weight_decay: 0.0005
weights: null
work_dir: /home/umurotti/remote_workspace/experiments/HandFormer/work_dirs/handformer_B21x8/
